
export const CONTACT_GET_SUCCESS = "CONTACT_GET_SUCCESS";
export const CONTACT_GET_FAILURE = "CONTACT_GET_FAILURE";

export const CATEGORYAS_GET_SUCCESS = "CATEGORYAS_GET_SUCCESS";
export const CATEGORYAS_GET_FAILURE = "CATEGORYAS_GET_FAILURE";

export const REQCATEGOGY_GET_SUCCESS = "REQCATEGOGY_GET_SUCCESS";
export const REQCATEGOGY_GET_FAILURE = "REQCATEGOGY_GET_FAILURE";